services:
  postgres:
    image: postgres:17
    container_name: subscription-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}           
      POSTGRES_USER: ${DB_USER}          
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
    ports:
      - "${DB_PORT}:5432"                
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: .                         
      dockerfile: Dockerfile
    container_name: subscription-app
    environment:
      SERVER_HOST: ${SERVER_HOST}        
      SERVER_PORT: ${SERVER_PORT}        
      DB_HOST: postgres                  
      DB_PORT: ${DB_PORT}                     
      DB_USER: ${DB_USER}                
      DB_PASSWORD: ${DB_PASSWORD}       
      DB_NAME: ${DB_NAME}               
      DB_SSLMODE: ${DB_SSLMODE}          
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"  
    depends_on:
      postgres:
        condition: service_healthy       

volumes:
  postgres_data:                      

