// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/subscriptions": {
            "get": {
                "description": "Возвращает детальную информацию о подписке по ее идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "подписки"
                ],
                "summary": "Получить подписку по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID подписки",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Найденная подписка",
                        "schema": {
                            "$ref": "#/definitions/github_com_ZeroZeroZerooZeroo_subscription-service_internal_model.Subscription"
                        }
                    },
                    "400": {
                        "description": "ID обязателен",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Подписка не найдена",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет данные существующей подписки. Все поля опциональны.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "подписки"
                ],
                "summary": "Обновить подписку",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID подписки",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления подписки",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ZeroZeroZerooZeroo_subscription-service_internal_model.UpdateSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Подписка успешно обновлена"
                    },
                    "400": {
                        "description": "Неверное тело запроса",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Подписка не найдена",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новую подписку для пользователя с автоматическим расчетом даты окончания (+1 месяц)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "подписки"
                ],
                "summary": "Создать новую подписку",
                "parameters": [
                    {
                        "description": "Данные для создания подписки",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ZeroZeroZerooZeroo_subscription-service_internal_model.CreateSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Созданная подписка",
                        "schema": {
                            "$ref": "#/definitions/github_com_ZeroZeroZerooZeroo_subscription-service_internal_model.Subscription"
                        }
                    },
                    "400": {
                        "description": "Неверное тело запроса",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет подписку по идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "подписки"
                ],
                "summary": "Удалить подписку",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID подписки",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Подписка успешно удалена"
                    },
                    "400": {
                        "description": "ID обязателен",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Подписка не найдена",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/subscriptions/list": {
            "get": {
                "description": "Возвращает пагинированный список всех подписок",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "подписки"
                ],
                "summary": "Список подписок",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Лимит (по умолчанию: 10, максимум: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение (по умолчанию: 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список подписок",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_ZeroZeroZerooZeroo_subscription-service_internal_model.Subscription"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/subscriptions/total-cost": {
            "post": {
                "description": "Рассчитывает общую стоимость подписок за указанный период с фильтрацией по пользователю и сервису",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "стоимость"
                ],
                "summary": "Расчет общей стоимости",
                "parameters": [
                    {
                        "description": "Данные для расчета стоимости",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ZeroZeroZerooZeroo_subscription-service_internal_model.CalculateCostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Результат расчета стоимости",
                        "schema": {
                            "$ref": "#/definitions/github_com_ZeroZeroZerooZeroo_subscription-service_internal_model.CalculateCostResponse"
                        }
                    },
                    "400": {
                        "description": "Неверное тело запроса",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_ZeroZeroZerooZeroo_subscription-service_internal_model.CalculateCostRequest": {
            "description": "Тело запроса для расчета общей стоимости подписок",
            "type": "object",
            "required": [
                "end_period",
                "service_name",
                "start_period",
                "user_id"
            ],
            "properties": {
                "end_period": {
                    "type": "string",
                    "example": "02-2025"
                },
                "service_name": {
                    "type": "string",
                    "example": "Yandex Plus"
                },
                "start_period": {
                    "type": "string",
                    "example": "01-2025"
                },
                "user_id": {
                    "type": "string",
                    "example": "60601fee-2bf1-4721-ae6f-7636e79a0cba"
                }
            }
        },
        "github_com_ZeroZeroZerooZeroo_subscription-service_internal_model.CalculateCostResponse": {
            "description": "Ответ с результатом расчета общей стоимости",
            "type": "object",
            "properties": {
                "end_period": {
                    "type": "string",
                    "example": "02-2025"
                },
                "service_name": {
                    "type": "string",
                    "example": "Yandex Plus"
                },
                "start_period": {
                    "type": "string",
                    "example": "01-2025"
                },
                "total_cost": {
                    "type": "integer",
                    "example": 18000
                },
                "user_id": {
                    "type": "string",
                    "example": "60601fee-2bf1-4721-ae6f-7636e79a0cba"
                }
            }
        },
        "github_com_ZeroZeroZerooZeroo_subscription-service_internal_model.CreateSubscriptionRequest": {
            "description": "Тело запроса для создания новой подписки",
            "type": "object",
            "required": [
                "price",
                "service_name",
                "start_date",
                "user_id"
            ],
            "properties": {
                "price": {
                    "type": "integer",
                    "example": 1500
                },
                "service_name": {
                    "type": "string",
                    "example": "Yandex Plus"
                },
                "start_date": {
                    "type": "string",
                    "example": "01-2025"
                },
                "user_id": {
                    "type": "string",
                    "example": "60601fee-2bf1-4721-ae6f-7636e79a0cba"
                }
            }
        },
        "github_com_ZeroZeroZerooZeroo_subscription-service_internal_model.Subscription": {
            "description": "Информация о подписке",
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string",
                    "example": "02-2025"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "price": {
                    "type": "integer",
                    "example": 1500
                },
                "service_name": {
                    "type": "string",
                    "example": "Yandex Plus"
                },
                "start_date": {
                    "type": "string",
                    "example": "01-2025"
                },
                "user_id": {
                    "type": "string",
                    "example": "60601fee-2bf1-4721-ae6f-7636e79a0cba"
                }
            }
        },
        "github_com_ZeroZeroZerooZeroo_subscription-service_internal_model.UpdateSubscriptionRequest": {
            "description": "Тело запроса для обновления существующей подписки",
            "type": "object",
            "properties": {
                "price": {
                    "type": "integer",
                    "example": 2000
                },
                "service_name": {
                    "type": "string",
                    "example": "Yandex Plus Premium"
                },
                "start_date": {
                    "type": "string",
                    "example": "02-2025"
                },
                "user_id": {
                    "type": "string",
                    "example": "60601fee-2bf1-4721-ae6f-7636e79a0cba"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Subscription Service API",
	Description:      "Сервис управления подписками с расчетом стоимости",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
